twig:
    paths:
        - '%kernel.project_dir%/../../../src/Shared/Infrastructure/Symfony/Profiler/templates'
    default_path: '%kernel.project_dir%/templates'
when@test:
    twig:
        strict_variables: true
