scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api_backend_php'
    scrape_interval: 5s
    static_configs:
      - targets: ['app-core-api_backend-php:8040']